// ╔════════════════════════════════════════════════════════════════╗
// ║              ПРЕСЕТ: АВТОЗАПЧАСТИ                              ║
// ╚════════════════════════════════════════════════════════════════╝

import { AppConfig } from '@/types/config';

export const autoPartsPreset: Partial<AppConfig> = {
  site: {
    name: 'AutoParts Pro',
    description: 'Магазин автозапчастей',
    logo: '/assets/logo.svg',
    favicon: '/assets/favicon.ico',
    contacts: {
      phone: '+7 (999) 555-44-33',
      email: 'zakaz@autoparts.ru',
      address: 'Москва, ул. Автомобильная, 15',
      workHours: 'Пн-Сб: 9:00-20:00',
      socials: {
        telegram: 'https://t.me/autoparts',
        whatsapp: 'https://wa.me/79995554433',
      },
    },
    currency: { code: 'RUB', symbol: '₽', position: 'after' },
    navigation: [
      { label: 'nav.catalog', href: '/catalog' },
      { label: 'nav.brands', href: '/brands' },
      { label: 'nav.delivery', href: '/delivery' },
      { label: 'nav.contacts', href: '/contacts' },
    ],
    seo: {
      titleTemplate: '%s | AutoParts Pro',
      defaultTitle: 'AutoParts Pro — Автозапчасти с доставкой',
      keywords: ['автозапчасти', 'запчасти для авто', 'купить запчасти'],
    },
  },

  theme: {
    colors: {
      primary: '#E63946',
      primaryHover: '#D62839',
      primaryLight: '#FFEBEE',
      secondary: '#1D3557',
      secondaryHover: '#14213D',
      accent: '#F4A261',
      accentHover: '#E76F51',
      background: '#FFFFFF',
      surface: '#F8F9FA',
      surfaceHover: '#E9ECEF',
      border: '#DEE2E6',
      text: '#212529',
      textMuted: '#6C757D',
      textInverse: '#FFFFFF',
      success: '#2A9D8F',
      error: '#E63946',
      warning: '#F4A261',
    },
    fonts: {
      heading: 'Roboto Condensed, sans-serif',
      body: 'Roboto, sans-serif',
    },
    borderRadius: {
      sm: '4px',
      md: '6px',
      lg: '8px',
      xl: '12px',
      full: '9999px',
    },
    shadows: {
      card: '0 1px 3px rgba(0, 0, 0, 0.12)',
      cardHover: '0 4px 12px rgba(0, 0, 0, 0.15)',
      dropdown: '0 8px 24px rgba(0, 0, 0, 0.18)',
      button: '0 2px 4px rgba(0, 0, 0, 0.08)',
    },
    transitions: {
      fast: '100ms',
      normal: '200ms',
      slow: '300ms',
    },
    darkMode: false,
  },

  product: {
    entityName: {
      singular: 'Запчасть',
      plural: 'Запчасти',
      genitive: 'запчастей',
    },
    fields: [
      {
        key: 'brand',
        label: 'Производитель',
        type: 'select',
        options: ['Bosch', 'NGK', 'Denso', 'Mann', 'Febi', 'TRW', 'Sachs'],
        filterable: true,
        showInCard: true,
        showInDetail: true,
        required: true,
      },
      {
        key: 'oem',
        label: 'OEM номер',
        type: 'text',
        searchable: true,
        showInCard: true,
        showInDetail: true,
      },
      {
        key: 'carBrand',
        label: 'Марка авто',
        type: 'select',
        options: ['Toyota', 'Honda', 'BMW', 'Mercedes', 'Audi', 'VW', 'Ford', 'Hyundai', 'Kia'],
        filterable: true,
        showInCard: true,
        showInDetail: true,
      },
      {
        key: 'carModel',
        label: 'Модель авто',
        type: 'text',
        filterable: true,
        showInCard: false,
        showInDetail: true,
      },
      {
        key: 'yearFrom',
        label: 'Год от',
        type: 'number',
        min: 1990,
        max: 2025,
        filterable: true,
        showInCard: false,
        showInDetail: true,
      },
      {
        key: 'yearTo',
        label: 'Год до',
        type: 'number',
        min: 1990,
        max: 2025,
        filterable: true,
        showInCard: false,
        showInDetail: true,
      },
      {
        key: 'condition',
        label: 'Состояние',
        type: 'select',
        options: ['Новая', 'Б/У', 'Восстановленная'],
        filterable: true,
        showInCard: true,
        showInDetail: true,
      },
      {
        key: 'warranty',
        label: 'Гарантия',
        type: 'text',
        suffix: 'мес.',
        showInCard: false,
        showInDetail: true,
      },
    ],
    sorting: [
      { key: 'price_asc', label: 'Сначала дешевле' },
      { key: 'price_desc', label: 'Сначала дороже' },
      { key: 'name_asc', label: 'По названию' },
      { key: 'popular', label: 'По популярности' },
    ],
    display: {
      showPrice: true,
      showOldPrice: true,
      showDiscount: true,
      showRating: false,
      showReviews: false,
      showStock: true,
      showSku: true,
      imagesPerProduct: 4,
    },
    card: {
      layout: 'horizontal',
      imageAspect: '1:1',
      showQuickView: false,
      showAddToCart: true,
      showWishlist: false,
      showCompare: true,
    },
  },

  features: {
    cart: { enabled: true, minOrder: 500, maxItems: 100, showQuantity: true },
    checkout: {
      guestCheckout: true,
      requirePhone: true,
      requireEmail: false,
      requireAddress: true,
      showComments: true,
      paymentMethods: ['cash', 'card'],
      deliveryMethods: ['pickup', 'courier', 'post', 'transport'],
    },
    auth: { enabled: false, providers: [] },
    wishlist: false,
    compare: true,
    reviews: false,
    search: true,
    filters: true,
    categories: true,
    brands: true,
    integrations: {
      analytics: { google: '', yandex: '' },
      chat: { enabled: true, provider: 'whatsapp' },
    },
    homepage: {
      heroBanner: true,
      featuredProducts: true,
      categories: true,
      benefits: true,
      testimonials: false,
      brands: true,
      newsletter: false,
    },
  },
};
